apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  default.conf: |
    upstream myapp {
        server app-blue:5000 weight=80;
        server app-green:5000 weight=20;
    }

    server {
        listen 80;
        location / {
            proxy_pass http://myapp;
        }
    }